/**
 * Country list for form dropdowns
 */

export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Belgium",
  "Switzerland",
  "Austria",
  "Ireland",
  "New Zealand",
  "Singapore",
  "Hong Kong",
  "Italy",
  "Spain",
  "Portugal",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "South Africa",
  "Nigeria",
  "Kenya",
  "India",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Malaysia",
  "Taiwan",
  "Israel",
  "United Arab Emirates",
  "Saudi Arabia",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "Other",
] as const;

export type Country = typeof COUNTRIES[number];
