// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wevjkggxaatdfihgkwxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldmprZ2d4YWF0ZGZpaGdrd3hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4NDIyMzEsImV4cCI6MjA4MzQxODIzMX0.Nms7XisVHQGu9Fe2dl909agObcuRYOLaOoMCF7u1rKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});